//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class booked_ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booked_ticket()
        {
            this.canceled_ticket = new HashSet<canceled_ticket>();
        }
    
        public int PNR { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<decimal> trainNo { get; set; }
        public string passengerName { get; set; }
        public int passengerAge { get; set; }
        public string ticketClass { get; set; }
        public double totalFare { get; set; }
        public System.DateTime bookingDateTime { get; set; }
    
        public virtual train_details train_details { get; set; }
        public virtual user_details user_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<canceled_ticket> canceled_ticket { get; set; }
    }
}
