//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class canceled_ticket
    {
        public int canceledId { get; set; }
        public Nullable<int> PNR { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<decimal> trainNo { get; set; }
        public System.DateTime cancellationDateTime { get; set; }
        public double refundAmount { get; set; }
    
        public virtual booked_ticket booked_ticket { get; set; }
        public virtual train_details train_details { get; set; }
        public virtual user_details user_details { get; set; }
    }
}
