//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat_availability
    {
        public int serialNo { get; set; }
        public Nullable<decimal> trainNo { get; set; }
        public int C1AC { get; set; }
        public int C2AC { get; set; }
        public int C3AC { get; set; }
        public int SL { get; set; }
    
        public virtual train_details train_details { get; set; }
    }
}
