//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Reservation_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Train_Reservation_DBEntities : DbContext
    {
        public Train_Reservation_DBEntities()
            : base("name=Train_Reservation_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_details> admin_details { get; set; }
        public virtual DbSet<booked_ticket> booked_ticket { get; set; }
        public virtual DbSet<canceled_ticket> canceled_ticket { get; set; }
        public virtual DbSet<seat_availability> seat_availability { get; set; }
        public virtual DbSet<train_details> train_details { get; set; }
        public virtual DbSet<user_details> user_details { get; set; }
        public virtual DbSet<train_classes> train_classes { get; set; }
    }
}
